#include "keys.h"

void init_keys(void){
  SET_DDR_IN(BUTTON_A_DDR, BUTTON_A_PIN);
  SET_PULLUP(BUTTON_A_PORT, BUTTON_A_PIN);
  SET_DDR_IN(BUTTON_B_DDR, BUTTON_B_PIN);
  SET_PULLUP(BUTTON_B_PORT, BUTTON_B_PIN);
  SET_DDR_IN(BUTTON_C_DDR, BUTTON_C_PIN);
  SET_PULLUP(BUTTON_C_PORT, BUTTON_C_PIN);
  SET_DDR_IN(BUTTON_UP_DDR, BUTTON_UP_PIN);
  SET_PULLUP(BUTTON_UP_PORT, BUTTON_UP_PIN);
  SET_DDR_IN(BUTTON_DOWN_DDR, BUTTON_DOWN_PIN);
  SET_PULLUP(BUTTON_DOWN_PORT, BUTTON_DOWN_PIN);
  SET_DDR_IN(BUTTON_LEFT_DDR, BUTTON_LEFT_PIN);
  SET_PULLUP(BUTTON_LEFT_PORT, BUTTON_LEFT_PIN);
  SET_DDR_IN(BUTTON_RIGHT_DDR, BUTTON_RIGHT_PIN);
  SET_PULLUP(BUTTON_RIGHT_PORT, BUTTON_RIGHT_PIN);
}