#include "pins.h"
#include "macro.h"

#ifndef SPEAKER_H
#define SPEAKER_H

// tone is generated by Timer0 on OC0B (PD5), CTC mode, toggle on compare match
// frequency range at 16 MHz: 31 Hz .. 8 MHz (audible part is enough)
#define SPEAKER_FREQ_MIN        31

void init_speaker(void);
void speaker_tone(uint16_t freq);
void speaker_off(void);

#endif
